import { Post, Profile, Category } from "../types";
import { CATEGORY_DEFINITIONS } from "./categories";

// Demo profiles
export const MOCK_PROFILES: Profile[] = [
  {
    id: "user-1",
    username: "swiftie_forever",
    display_name: "Swiftie Forever",
    bio: "Poet and Taylor fan since 2008",
    avatar_url: null,
    membership_tier: "annual",
    stripe_customer_id: null,
    stripe_subscription_id: null,
    subscription_end_date: null,
    is_admin: false,
    post_count: 5,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "user-2",
    username: "eras_poet",
    display_name: "Eras Poet",
    bio: "Writing through every era",
    avatar_url: null,
    membership_tier: "lifetime",
    stripe_customer_id: null,
    stripe_subscription_id: null,
    subscription_end_date: null,
    is_admin: false,
    post_count: 12,
    created_at: "2024-02-01T10:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
  },
  {
    id: "admin-1",
    username: "admin",
    display_name: "Portal Admin",
    bio: "Portal administrator",
    avatar_url: null,
    membership_tier: "lifetime",
    stripe_customer_id: null,
    stripe_subscription_id: null,
    subscription_end_date: null,
    is_admin: true,
    post_count: 0,
    created_at: "2024-01-01T10:00:00Z",
    updated_at: "2024-01-01T10:00:00Z",
  },
];

// Generate mock categories from definitions
export const MOCK_CATEGORIES: Category[] = CATEGORY_DEFINITIONS.map(
  (def, i) => ({
    id: `cat-${i + 1}`,
    name: def.name,
    slug: def.slug,
    description: def.description,
    type: def.type,
    color: def.color,
    year_info: def.year_info,
    post_count: Math.floor(Math.random() * 20) + 1,
    created_at: "2024-01-01T00:00:00Z",
  }),
);

export const MOCK_POSTS: Post[] = [
  {
    id: "post-1",
    author_id: "user-1",
    category_id: "cat-1",
    title: "A Debut Summer",
    content_type: "poem",
    content: `In a small town where the crickets sing,\nA girl with a guitar found everything.\nShe wrote of love on yellow notepad pages,\nBuilding dreams across the ages.\n\nWith sequins bright and boots so clean,\nShe dared to say the things she'd seen.\nAnd when the spotlight finally found her face,\nShe filled that debut stage with grace.`,
    video_url: null,
    excerpt: "A poem celebrating Taylor's small-town beginnings.",
    is_approved: true,
    is_featured: true,
    view_count: 142,
    like_count: 38,
    created_at: "2024-03-10T14:00:00Z",
    updated_at: "2024-03-10T14:00:00Z",
    author: MOCK_PROFILES[0],
    category: MOCK_CATEGORIES[0],
  },
  {
    id: "post-2",
    author_id: "user-2",
    category_id: "cat-4",
    title: "All Too Well (A Fan's Story)",
    content_type: "story",
    content: `She kept the scarf in a box at the back of her wardrobe. Three years, and she hadn't been able to throw it away. It smelled like someone else's laundry detergent, someone else's autumn, someone else's everything.\n\nHer roommate had asked about it once. "Why do you keep it if it hurts?" she'd asked, genuinely puzzled the way only people who hadn't loved that deeply could be.\n\n"Because forgetting would be worse," she'd said. And that was the truth of it — the whole complicated, aching truth of it.`,
    video_url: null,
    excerpt: "A fan story exploring the feeling behind the legendary 10-minute track.",
    is_approved: true,
    is_featured: true,
    view_count: 289,
    like_count: 74,
    created_at: "2024-03-15T09:30:00Z",
    updated_at: "2024-03-15T09:30:00Z",
    author: MOCK_PROFILES[1],
    category: MOCK_CATEGORIES[3],
  },
  {
    id: "post-3",
    author_id: "user-1",
    category_id: "cat-17",
    title: "Eras Tour Medley",
    content_type: "poem",
    content: `Thirteen eras, one night to hold them all,\nFrom country roads to midnight's call.\nSequins shift from gold to midnight blue,\nEvery version of her, every version true.\n\nThe Eras Tour — a journey through the years,\nOf love and loss and hard-won souvenirs.\nIn friendship bracelets traded hand to hand,\nA generation bound by one woman's stand.`,
    video_url: null,
    excerpt: "A poem weaving through all thirteen eras.",
    is_approved: true,
    is_featured: false,
    view_count: 95,
    like_count: 27,
    created_at: "2024-04-01T16:00:00Z",
    updated_at: "2024-04-01T16:00:00Z",
    author: MOCK_PROFILES[0],
    category: MOCK_CATEGORIES[16],
  },
  {
    id: "post-4",
    author_id: "user-2",
    category_id: "cat-18",
    title: "The Showgirl's First Chapter",
    content_type: "story",
    content: `She'd always known she was meant for stages. The question was which kind.\n\nThe story Taylor described — a girl who reinvents herself so many times she forgets which version is real — felt true in a way that fiction rarely does. Not because it was autobiographical, but because it was universal.\n\nWhen the showgirl finally stops performing, what does she find underneath all the costumes? That's the question this story dared to ask. And the answer, like all the best Taylor Swift songs, was both heartbreaking and hopeful.`,
    video_url: null,
    excerpt: "A story inspired by the concept Taylor outlined on The Late Show.",
    is_approved: true,
    is_featured: true,
    view_count: 201,
    like_count: 56,
    created_at: "2024-04-10T11:00:00Z",
    updated_at: "2024-04-10T11:00:00Z",
    author: MOCK_PROFILES[1],
    category: MOCK_CATEGORIES[17],
  },
];
